version: "3"

services:
  api-service:
    build: ./api-service
    container_name: coastr-college-api
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production

  # app:
  #   container_name: "coastr-college-app"
  #   build:
  #     context: "."
  #     dockerfile: "./app/Dockerfile"
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./app:/usr/app
  #   ports:
  #     - "4100:4100"

  mongo:
    container_name: "coastr-college-mongo"
    image: mongo
    ports:
      - "4001:27017"

  redis:
    container_name: "coastr-college-redis"
    image: redis
    ports:
      - "4002:6379"