version: 3

services:
  api-service:
    build: ./api-service
    container_name: coastr-college-api
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    container_name: coastr-college-client
    ports:
      - 4100:4100
    depends_on:
      - api
    environment:
      - NODE_ENV=production

  mongo:
    container_name: coastr-college-mongo
    image: mongo
    ports:
      - 4001:27017

  redis:
    container_name: coastr-college-redis
    image: redis
    ports:
      - 4002:6379