/* LoginPage */
export const LOGIN_PAGE_SHOW_LOGIN_FORM = 'LOGIN_PAGE_SHOW_LOGIN_FORM';
export const RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE';
export const UPDATE_LOGIN_PAGE_FORM_FIELD = 'UPDATE_LOGIN_PAGE_FORM_FIELD';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

/* SignupPage */
export const SUBMIT_SIGNUP_REQUEST = 'SUBMIT_SIGNUP_REQUEST';
export const SUBMIT_SIGNUP_SUCCESS = 'SUBMIT_SIGNUP_SUCCESS';
export const SUBMIT_SIGNUP_ERROR = 'SUBMIT_SIGNUP_ERROR';

export const RESET_SIGNUP_PAGE_META = 'RESET_SIGNUP_PAGE_META';
export const RESET_SIGNUP_PAGE = 'RESET_SIGNUP_PAGE';

/* CollegesPage */
export const GET_COLLEGES_PAGE_REQUEST = 'GET_COLLEGES_PAGE_REQUEST';
export const GET_COLLEGES_PAGE_SUCCESS = 'GET_COLLEGES_PAGE_SUCCESS';
export const GET_COLLEGES_PAGE_ERROR = 'GET_COLLEGES_PAGE_ERROR';
export const RESET_COLLEGES_PAGE_META = 'RESET_COLLEGES_PAGE_META';
export const RESET_COLLEGES_PAGE = 'RESET_COLLEGES_PAGE';

/* CollegeDetailsPage */
export const GET_COLLEGE_BASIC_REQUEST = 'GET_COLLEGE_BASIC_REQUEST';
export const GET_COLLEGE_BASIC_SUCCESS = 'GET_COLLEGE_BASIC_SUCCESS';
export const GET_COLLEGE_BASIC_ERROR = 'GET_COLLEGE_BASIC_ERROR';
export const RESET_COLLEGE_BASIC_META = 'RESET_COLLEGE_BASIC_META';
export const RESET_COLLEGE_BASIC = 'RESET_COLLEGE_BASIC';

export const SUBMIT_COLLEGE_DETAIL_REQUEST = 'SUBMIT_COLLEGE_DETAIL_REQUEST';
export const SUBMIT_COLLEGE_DETAIL_SUCCESS = 'SUBMIT_COLLEGE_DETAIL_SUCCESS';
export const SUBMIT_COLLEGE_DETAIL_ERROR = 'SUBMIT_COLLEGE_DETAIL_ERROR';

/* StudentsPage */
export const GET_STUDENTS_PAGE_REQUEST = 'GET_STUDENTS_PAGE_REQUEST';
export const GET_STUDENTS_PAGE_SUCCESS = 'GET_STUDENTS_PAGE_SUCCESS';
export const GET_STUDENTS_PAGE_ERROR = 'GET_STUDENTS_PAGE_ERROR';
export const RESET_STUDENTS_PAGE_META = 'RESET_STUDENTS_PAGE_META';
export const RESET_STUDENTS_PAGE = 'RESET_STUDENTS_PAGE';

/* StudentDetailsPage */
export const GET_STUDENT_BASIC_REQUEST = 'GET_STUDENT_BASIC_REQUEST';
export const GET_STUDENT_BASIC_SUCCESS = 'GET_STUDENT_BASIC_SUCCESS';
export const GET_STUDENT_BASIC_ERROR = 'GET_STUDENT_BASIC_ERROR';
export const RESET_STUDENT_BASIC_META = 'RESET_STUDENT_BASIC_META';
export const RESET_STUDENT_BASIC = 'RESET_STUDENT_BASIC';

export const SUBMIT_STUDENT_DETAIL_REQUEST = 'SUBMIT_STUDENT_DETAIL_REQUEST';
export const SUBMIT_STUDENT_DETAIL_SUCCESS = 'SUBMIT_STUDENT_DETAIL_SUCCESS';
export const SUBMIT_STUDENT_DETAIL_ERROR = 'SUBMIT_STUDENT_DETAIL_ERROR';